DROP DATABASE IF EXISTS PROJETO;
CREATE DATABASE PROJETO;

USE PROJETO;

DROP TABLE IF EXISTS BAIRRO;
DROP TABLE IF EXISTS ENDERECO;

DROP TABLE IF EXISTS TIPO_P_F;
DROP TABLE IF EXISTS P_PEDE_S;

DROP TABLE IF EXISTS F_F_SERVICO;
DROP TABLE IF EXISTS F_FORNECE_P;

DROP TABLE IF EXISTS CONTATO;
DROP TABLE IF EXISTS FISICA;
DROP TABLE IF EXISTS JURIDICA;
DROP TABLE IF EXISTS PESSOAS;
DROP TABLE IF EXISTS SERVICO;
DROP TABLE IF EXISTS FORNECEDOR;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS CAIXA_MENSAL;
DROP TABLE IF EXISTS BOLETOS;

# entidades

CREATE TABLE BAIRRO(
	ID INT PRIMARY KEY,
    NOME VARCHAR(300),
    DESCRICAO VARCHAR(600)
);

CREATE TABLE ENDERECO(
	CEP INTEGER PRIMARY KEY,
    TIPO_LOCAL VARCHAR(300),
    COMPLEMENTO VARCHAR(600),
    LOGRADOURO VARCHAR(600),
    NUMERO INT,
    ID_BAIRRO INT,
    FOREIGN KEY(ID_BAIRRO) REFERENCES BAIRRO(ID)
);

CREATE TABLE PESSOAS(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR(200),
    SOBRENOME VARCHAR(200),
    DATA_REGISTRO DATE,
	CEP_ENDERECO INT,
    FOREIGN KEY(CEP_ENDERECO) REFERENCES ENDERECO(CEP)
);

CREATE TABLE CONTATO(
	TELEFONE CHAR(8),
    EMAIL VARCHAR(200),
    CELULAR CHAR(9),
    ID_P INTEGER PRIMARY KEY,
    FOREIGN KEY (ID_P) REFERENCES PESSOAS(ID)
);

CREATE TABLE JURIDICA(
	CNPJ CHAR(14),
    IE INTEGER,
    IM INTEGER,
    ID_P INTEGER,
    PRIMARY KEY(ID_P,CNPJ),
    FOREIGN KEY(ID_P) REFERENCES PESSOAS(ID) ON DELETE CASCADE
);

CREATE TABLE FISICA(
	ID_P INTEGER PRIMARY KEY,
	CPF CHAR(11),
    FOREIGN KEY(ID_P) REFERENCES PESSOAS(ID) ON DELETE CASCADE 
);

CREATE TABLE SERVICO(
	ID INTEGER,
    PRECO DECIMAL(10,2),
    DATA_INICIO_S DATE,
    DATA_FIM_S DATE,
    DESCRICAO VARCHAR(500),
    PRIMARY KEY(ID)
);

CREATE TABLE FORNECEDOR(
	CNPJ CHAR(14) PRIMARY KEY,
    NOME_FANTASIA VARCHAR(300),
    IE INTEGER
);

CREATE TABLE PRODUTO(
	ID INTEGER PRIMARY KEY,
    QTD INTEGER,
    VALOR_QTD DECIMAL(10,2),
    TIPO_MEDIDA_PRODUTO VARCHAR(7),
    NOME VARCHAR(200),
    DECRICAO VARCHAR(500),
    DISPONIBILIDADE CHAR(3)
);

CREATE TABLE CAIXA_MENSAL(
	MES_ANO VARCHAR(7) PRIMARY KEY,
    ID_PF INTEGER NOT NULL,
    VALOR_ENTRADA DECIMAL(10,2),
    VALOR_SAIDA DECIMAL(10,2),
    LUCRO DECIMAL(10,2),
    DESCRICAO_GASTO VARCHAR(600),
    DESCRICAO_ENTRADA VARCHAR(600),
    FOREIGN KEY(ID_PF) REFERENCES FISICA(ID_P)
);

CREATE TABLE BOLETOS(
	ID INTEGER PRIMARY KEY,
    MES_ANOC VARCHAR(7) NOT NULL,
    NOME_FATURA VARCHAR(200),
    VALOR DECIMAL(10,2),
    DIA_VENCIMENTO DATE,
    DIA_PAGO DATE,
    FOREIGN KEY(MES_ANOC) REFERENCES CAIXA_MENSAL(MES_ANO)
);

#relações e normalização

CREATE TABLE P_MORA_E(
	ID_P INTEGER,
    CEP_E INTEGER,
    PRIMARY KEY(ID_P,CEP_E),
    FOREIGN KEY(ID_P) REFERENCES PESSOAS(ID),
    FOREIGN KEY(CEP_E) REFERENCES ENDERECO(CEP)
);

CREATE TABLE F_FORNECE_P(
	CNPJ_F CHAR(14),
    ID_P INTEGER,
    PRIMARY KEY(CNPJ_F,ID_P),
    FOREIGN KEY(CNPJ_F) REFERENCES FORNECEDOR(CNPJ),
	FOREIGN KEY(ID_P) REFERENCES PRODUTO(ID)
);

CREATE TABLE E_NO_B(
	CEP_E INTEGER,
    ID_B INTEGER,
    PRIMARY KEY(CEP_E,ID_B),
    FOREIGN KEY(CEP_E) REFERENCES ENDERECO(CEP),
    FOREIGN KEY(ID_B) REFERENCES BAIRRO(ID) 
);

CREATE TABLE S_USA_P(
	ID_S INTEGER,
    ID_P INTEGER,
    PRIMARY KEY(ID_S,ID_P),
	FOREIGN KEY(ID_S) REFERENCES SERVICO(ID),
    FOREIGN KEY(ID_P) REFERENCES PRODUTO(ID)
);

#normalizacao pessoa fisica funcionario

CREATE TABLE TIPO_P_F(
	ID_F INTEGER NOT NUll,
    TIPO_PESSOA VARCHAR(15),
	FOREIGN KEY(ID_F) REFERENCES FISICA(ID_P),
    SALARIO FLOAT,
    CARGA_HORARIO INTEGER,
    DATA_INICO_TRABALHO DATE,
    PRIMARY KEY(ID_F,TIPO_PESSOA)
);

#servico 

CREATE TABLE F_F_SERVICO(
	ID_SERVICO INTEGER,
    ID_PF INTEGER NOT NULL,
    PRIMARY KEY(ID_SERVICO,ID_PF),
    FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO(ID),
    FOREIGN KEY (ID_PF) REFERENCES FISICA(ID_P)
);

CREATE TABLE P_PEDE_S(
	ID_P INTEGER NOT NULL,
    ID_S INTEGER NOT NULL,
	PRIMARY KEY(ID_P,ID_S),
    FOREIGN KEY(ID_P) REFERENCES PESSOAS(ID),
    FOREIGN KEY(ID_S) REFERENCES SERVICO(ID)
);
