DROP DATABASE IF EXISTS PROJETO;
CREATE DATABASE PROJETO;

USE PROJETO;


#endereço

DROP TABLE IF EXISTS CIDADE;
DROP TABLE IF EXISTS BAIRRO;
DROP TABLE IF EXISTS ENDERECO;


#relacionamentos

DROP TABLE IF EXISTS PF_E_F;
DROP TABLE IF EXISTS FORNCEDOR_TEM_CONTATO;
DROP TABLE IF EXISTS PESSOA_TEM_CONTATO;
DROP TABLE IF EXISTS DADOS_FUNCIONARIO;
DROP TABLE IF EXISTS FORNECEDOR_FORNECE_PRODUTO;
DROP TABLE IF EXISTS SERVICO_USA_PRODUTO;
DROP TABLE IF EXISTS FUNCIONARIO_FAZ_SERVICO;
DROP TABLE IF EXISTS PESSOA_PEDE_SERVICO;

#faz parte de pessoas ou fornecedor

DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS CONTATO;

#fornecedor

DROP TABLE IF EXISTS FORNECEDOR;

#pessoas
DROP TABLE IF EXISTS DADOS;
DROP TABLE IF EXISTS FISICA;
DROP TABLE IF EXISTS JURIDICA;
DROP TABLE IF EXISTS PESSOAS;

#serviço e produto
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS SERVICO;
DROP TABLE IF EXISTS PRODUTO;


#caixa da tapeçaria
DROP TABLE IF EXISTS CAIXA_MENSAL;
DROP TABLE IF EXISTS BOLETOS;

# entidades

#ENDEREÇO

CREATE TABLE CIDADE(
	ID INTEGER PRIMARY KEY,
	NOME VARCHAR(200),
    UF VARCHAR(4)
);

CREATE TABLE BAIRRO(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_CIDADE INTEGER NOT NULL,
    NOME VARCHAR(300),
    FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID)
);

CREATE TABLE ENDERECO(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CEP INTEGER,
    COMPLEMENTO VARCHAR(600),
    LOGRADOURO VARCHAR(600),
    NUMERO INT,
    ID_BAIRRO INTEGER NOT NULL,
    FOREIGN KEY(ID_BAIRRO) REFERENCES BAIRRO(ID)
);


#PESSOAS
CREATE TABLE PESSOAS(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200),
    SOBRENOME VARCHAR(200),
    DATA_REGISTRO DATE,
	ID_ENDERECO INT NOT NULL,
    FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID)
);

CREATE TABLE CONTATO(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TELEFONE VARCHAR(11),
    EMAIL VARCHAR(200),
    CELULAR VARCHAR(12)
);

CREATE TABLE JURIDICA(
	CNPJ CHAR(14),
    IE INTEGER,
    ID_P INTEGER,
    PRIMARY KEY(ID_P,CNPJ),
    FOREIGN KEY(ID_P) REFERENCES PESSOAS(ID) ON DELETE CASCADE
);

CREATE TABLE FISICA(
	ID_P INTEGER PRIMARY KEY,
	CPF CHAR(11),
    GENERO VARCHAR(2),
    FOREIGN KEY(ID_P) REFERENCES PESSOAS(ID) ON DELETE CASCADE 
);

CREATE TABLE FUNCAO(
	AVALIACAO INTEGER PRIMARY KEY,
    FUNCAO VARCHAR(30)
);

CREATE TABLE DADOS(
		ID INTEGER PRIMARY KEY,
        SALARIO DECIMAL(10,2),
        CARGA_HORARIA INTEGER

);

#SERVIÇO FORNECEDOR

CREATE TABLE SERVICO(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRECO DECIMAL(10,2),
    DATA_INICIO_S DATE,
    DATA_FIM_S DATE,
    DESCRICAO VARCHAR(500)
   
);

CREATE TABLE FORNECEDOR(
	CNPJ CHAR(14) PRIMARY KEY,
    NOME_FANTASIA VARCHAR(300),
    IE INTEGER
);


#PRODUTO

CREATE TABLE CATEGORIA(
	ID INTEGER PRIMARY KEY,
    GRUPO VARCHAR(200),
    NOME VARCHAR(200),
    COR VARCHAR(15)
);

CREATE TABLE PRODUTO(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIA INTEGER,
    QTD INTEGER,
    VALOR_QTD DECIMAL(10,2),
    TIPO_MEDIDA_PRODUTO VARCHAR(7),
    DISPONIBILIDADE CHAR(3),
    FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

#CAIXA
CREATE TABLE CAIXA_MENSAL(
	MES_ANO VARCHAR(7) PRIMARY KEY,
    ID_PF INTEGER NOT NULL,
    VALOR_ENTRADA DECIMAL(10,2),
    VALOR_SAIDA DECIMAL(10,2),
    LUCRO DECIMAL(10,2),
    DESCRICAO_GASTO VARCHAR(600),
    DESCRICAO_ENTRADA VARCHAR(600),
    FOREIGN KEY(ID_PF) REFERENCES FISICA(ID_P)
);

CREATE TABLE BOLETOS(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MES_ANOC VARCHAR(7) NOT NULL,
    NOME_FATURA VARCHAR(200),
    VALOR DECIMAL(10,2),
    DIA_VENCIMENTO DATE,
    DIA_PAGO DATE,
    FOREIGN KEY(MES_ANOC) REFERENCES CAIXA_MENSAL(MES_ANO)
);

#relações

CREATE TABLE PF_E_F(
	ID_F INTEGER,
    AVALIACAO_F INTEGER,
    PRIMARY KEY(ID_F,AVALIACAO_F),
    FOREIGN KEY(ID_F) REFERENCES FISICA(ID_P),
    FOREIGN KEY(AVALIACAO_F) REFERENCES FUNCAO(AVALIACAO)
);

CREATE TABLE FORNCEDOR_TEM_CONTATO(
	CNPJ_FORNECEDOR CHAR(14),
    ID_CONTATO INTEGER,
    FOREIGN KEY(CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ),
    FOREIGN KEY(ID_CONTATO) REFERENCES CONTATO(ID)
);

CREATE TABLE PESSOA_TEM_CONTATO(
	ID_PESSOAS INTEGER,
    ID_CONTATO INTEGER,
    FOREIGN KEY(ID_PESSOAS) REFERENCES PESSOAS(ID),
    FOREIGN KEY(ID_CONTATO) REFERENCES CONTATO(ID)
);

CREATE TABLE DADOS_FUNCIONARIO(
	ID_DADOS  INTEGER ,
    AVALIACAO_FUNCAO INTEGER,
    PRIMARY KEY(ID_DADOS,AVALIACAO_FUNCAO),
    FOREIGN KEY(ID_DADOS) REFERENCES DADOS(ID),
	FOREIGN KEY(AVALIACAO_FUNCAO) REFERENCES FUNCAO(AVALIACAO)
    
);

CREATE TABLE FORNECEDOR_FORNECE_PRODUTO(
	CNPJ_F CHAR(14),
    ID_P INTEGER,
    PRIMARY KEY(CNPJ_F,ID_P),
    FOREIGN KEY(CNPJ_F) REFERENCES FORNECEDOR(CNPJ),
	FOREIGN KEY(ID_P) REFERENCES PRODUTO(ID)
);

CREATE TABLE SERVICO_USA_PRODUTO(
	ID_S INTEGER,
    ID_P INTEGER,
    PRIMARY KEY(ID_S,ID_P),
	FOREIGN KEY(ID_S) REFERENCES SERVICO(ID),
    FOREIGN KEY(ID_P) REFERENCES PRODUTO(ID)
);

CREATE TABLE FUNCIONARIO_FAZ_SERVICO(
	ID_SERVICO INTEGER,
    ID_PF INTEGER NOT NULL,
    PRIMARY KEY(ID_SERVICO,ID_PF),
    FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO(ID),
    FOREIGN KEY (ID_PF) REFERENCES FISICA(ID_P)
);

CREATE TABLE PESSOA_PEDE_SERVICO(
	ID_P INTEGER NOT NULL,
    ID_S INTEGER NOT NULL,
	PRIMARY KEY(ID_P,ID_S),
    FOREIGN KEY(ID_P) REFERENCES PESSOAS(ID),
    FOREIGN KEY(ID_S) REFERENCES SERVICO(ID)
);
